1.2.xx: Several changes in command-line interface; includes updated GuiE spec; some obsolete commands removed. In general, a backwards incompatible command-line interface.  Preliminary tests on most common commands OK (cd tests && make ALL).  Exhaustive testing pending.

diff --git a/starspan.in b/starspan.in
--- a/starspan.in
+++ b/starspan.in
@@ -22,7 +22,7 @@ export PATH=@GDAL_PREFIX@/bin:@GEOS_PREFIX@/bin:$PATH
 # Required by the --gui option:
 #      guie.jar
 #      starspan.guie
-# guie.jar can be downloaded from https://sourceforge.net/project/showfiles.php?group_id=141010
+# guie.jar can be downloaded from http://sf.net/project/showfiles.php?group_id=141010
 #
 # Required by the --view_geometries option:
 #      plotapplication.jar
@@ -41,7 +41,7 @@ export PATH=@GDAL_PREFIX@/bin:@GEOS_PREFIX@/bin:$PATH
 JARS=$BINDIR/starspan.jars/
 
 usage() {
-	cat << EOF
+    cat << EOF
 
 starspan extended usage:
 
@@ -51,7 +51,7 @@ starspan extended usage:
     starspan --view_geometries dumped_geometries.csv
         launches the ptPlot application with the given file.
         Normally dumped_geometries.csv was generated by 
-		"starspan --dump_geometries dumped_geometries.csv ..."
+        "starspan --dump_geometries dumped_geometries.csv ..."
             
     starspan --test args...
         launches the JTS Test Runner
@@ -67,19 +67,19 @@ starspan extended usage:
 
     starspan --run cmd args ...
         Runs a command under the same environment as that of the
-		StarSpan system.
+        StarSpan system.
         E.g.  starspan --run ogrinfo -al a_vector_file 
 
 EOF
-	return;
+    return;
 }
 
 if [ "$1" = "--xhelp" ]; then
-	usage
-	exit
+    usage
+    exit
 
 elif [ "$1" = "--gui" ]; then
-	echo "[Launching StarSpan GUI...]"
+    echo "[Launching StarSpan GUI...]"
     if [ ! -x `which java` ]; then
         echo "Command 'java' is required to launch this application."
         exit 1
@@ -88,55 +88,55 @@ elif [ "$1" = "--gui" ]; then
         echo "Cannot open $BINDIR/starspan.guie"
         exit 1
     fi
-	shift
-	CP=$CLASSPATH
-	CP=$JARS/guie.jar:$CP
-	java -Xmx256m -cp "$CP" guie.Guie $BINDIR/starspan.guie "$@"
-	ret=$?
-	if [ "$ret" != 0 ]; then
-		echo "[exit code=$ret -- a missing component in your classpath?]"
-	fi
+    shift
+    CP=$CLASSPATH
+    CP=$JARS/guie.jar:$CP
+    java -Xmx256m -cp "$CP" guie.Guie $BINDIR/starspan.guie "$@"
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        echo "[exit code=$ret -- a missing component in your classpath?]"
+    fi
 
 elif [ "$1" = "--view_geometries" ]; then
-	echo "[Launching ptplot...]"
-	shift
-	CP=$CLASSPATH
-	CP=$JARS/plotapplication.jar:$CP
-	java -Xmx256m -cp "$CP" ptolemy.plot.PlotApplication "$@"
-	ret=$?
-	if [ "$ret" != 0 ]; then
-		echo "[exit code=$ret -- a missing component in your classpath?]"
-	fi
+    echo "[Launching ptplot...]"
+    shift
+    CP=$CLASSPATH
+    CP=$JARS/plotapplication.jar:$CP
+    java -Xmx256m -cp "$CP" ptolemy.plot.PlotApplication "$@"
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        echo "[exit code=$ret -- a missing component in your classpath?]"
+    fi
 
 elif [ "$1" = "--test" ]; then
-	echo "[Launching JTS TopologyTestApp...]"
-	shift
-	CP=$CLASSPATH
-	for i in $JARS/*.jar; do CP=$i:$CP; done
-	java -Xmx256m -cp "$CP" com.vividsolutions.jtstest.testrunner.TopologyTestApp "$@"
-	ret=$?
-	if [ "$ret" != 0 ]; then
-		echo "[exit code=$ret -- a missing component in your classpath?]"
-	fi
+    echo "[Launching JTS TopologyTestApp...]"
+    shift
+    CP=$CLASSPATH
+    for i in $JARS/*.jar; do CP=$i:$CP; done
+    java -Xmx256m -cp "$CP" com.vividsolutions.jtstest.testrunner.TopologyTestApp "$@"
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        echo "[exit code=$ret -- a missing component in your classpath?]"
+    fi
 
 elif [ "$1" = "--jts" ]; then
-	echo "[Launching JTSTestBuilder...]"
-	shift
-	CP=$CLASSPATH
-	for i in $JARS/*.jar; do CP=$i:$CP; done
-	java -Xmx256m -cp "$CP" com.vividsolutions.jtstest.testbuilder.JTSTestBuilder "$@"
-	ret=$?
-	if [ "$ret" != 0 ]; then
-		echo "[exit code=$ret -- a missing component in your classpath?]"
-	fi
+    echo "[Launching JTSTestBuilder...]"
+    shift
+    CP=$CLASSPATH
+    for i in $JARS/*.jar; do CP=$i:$CP; done
+    java -Xmx256m -cp "$CP" com.vividsolutions.jtstest.testbuilder.JTSTestBuilder "$@"
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        echo "[exit code=$ret -- a missing component in your classpath?]"
+    fi
 
 elif [ "$1" = "--run" ]; then
-	shift
-	echo "[Running " "$@" "]"
-	"$@"
+    shift
+    echo "[Running " "$@" "]"
+    "$@"
 
 else
-	# call starspan2
-	$STARSPAN2 "$@"
+    # call starspan2
+    $STARSPAN2 "$@"
 fi
 
